# This is a basic workflow to help you get started with Actions

name: Build CI v2

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          export cpath=$(pwd)
          sudo apt update
          sudo apt-get install git re2c cmake clang python3 tree -y
          git clone http://github.com/ninja-build/ninja
          cd ninja
          ./configure.py --bootstrap
          sudo cp ninja /usr/bin/
          sudo apt-get install ninja-build
          echo #######NINJA ccccc BUILD
          ninja --version
          cd ..
          echo #######GIT1 ccccc BUILD
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH=$cpath/depot_tools:$PATH
          export XWALK_OS_ANDROID=1
          echo #######GCLIENT ccccc BUILD
          gclient config --name=src/xwalk https://github.com/ks32/crosswalk.git@origin/ks_chromium_77
          export fiv=$(find -name ".gclient" | sed -n "1p")
          echo $fiv
          echo "target_os = ['android']" >>$fiv
          ls -la
          gclient sync
          gn args out/Default_x64
          ninja -k3 -C out/Default_x64 xwalk_core_library || ninja -k3 -C out/Default_x64 xwalk_core_library
          echo okay
          echo #######TREE ccccc BUILD
          tree >tree.txt
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: |
            **/*.arr
            **/*.jar
            **/*.so
            **/*.aar
            tree.txt
